version: "3.8"

services:
  api-gateway:
    build:
      context: .
      dockerfile: ./docker/api-gateway.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - NODE_ENV=development
      - AUTH_SERVICE_URL=http://auth-service:8001
      - QUANTUM_SERVICE_URL=http://quantum-service:8002
      - LOTTERY_SERVICE_URL=http://lottery-service:8003
      - BLOCKCHAIN_SERVICE_URL=http://blockchain-service:8004
    depends_on:
      - quantum-service
      - lottery-service
      - blockchain-service
      - auth-service
    networks:
      - qupot-network
    volumes:
      - ./apps/api-gateway:/app/apps/api-gateway
      - ./packages:/app/packages
      - node_modules_api_gateway:/app/apps/api-gateway/node_modules

  quantum-service:
    build:
      context: .
      dockerfile: ./docker/quantum-service.Dockerfile
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - ENVIRONMENT=development
    networks:
      - qupot-network
    volumes:
      - ./apps/quantum-service:/app/apps/quantum-service

  lottery-service:
    build:
      context: .
      dockerfile: ./docker/lottery-service.Dockerfile
    ports:
      - "8003:8003"
    environment:
      - PORT=8003
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=lottery
    depends_on:
      - postgres
    networks:
      - qupot-network
    volumes:
      - ./apps/lottery-service:/app/apps/lottery-service
      - ./packages:/app/packages
      - node_modules_lottery_service:/app/apps/lottery-service/node_modules

  blockchain-service:
    build:
      context: .
      dockerfile: ./docker/blockchain-service.Dockerfile
    ports:
      - "8004:8004"
    environment:
      - PORT=8004
      - NODE_ENV=development
      - HARDHAT_NETWORK=hardhat
    networks:
      - qupot-network
    volumes:
      - ./apps/blockchain-service:/app/apps/blockchain-service
      - ./packages:/app/packages
      - node_modules_blockchain_service:/app/apps/blockchain-service/node_modules

  auth-service:
    build:
      context: .
      dockerfile: ./docker/auth-service.Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=auth_service
    depends_on:
      - postgres
    networks:
      - qupot-network
    volumes:
      - ./apps/auth-service:/app/apps/auth-service
      - ./packages:/app/packages
      - node_modules_auth_service:/app/apps/auth-service/node_modules

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=lottery,auth_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    networks:
      - qupot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  qupot-network:
    driver: bridge

volumes:
  postgres_data:
  node_modules_api_gateway:
  node_modules_lottery_service:
  node_modules_blockchain_service:
  node_modules_auth_service:
